services:
  homepage:
    image: gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./public/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: "Europe/Helsinki"
      HOMEPAGE_ALLOWED_HOSTS: "*"
      HOMEPAGE_VAR_PROXMOX1_URL: ${HOMEPAGE_VAR_PROXMOX1_URL}
      HOMEPAGE_VAR_PROXMOX1_HREF: ${HOMEPAGE_VAR_PROXMOX1_HREF}
      HOMEPAGE_VAR_PROXMOX2_URL: ${HOMEPAGE_VAR_PROXMOX2_URL}
      HOMEPAGE_VAR_PROXMOX2_HREF: ${HOMEPAGE_VAR_PROXMOX2_HREF}
      HOMEPAGE_VAR_PROXMOX3_URL: ${HOMEPAGE_VAR_PROXMOX3_URL}
      HOMEPAGE_VAR_PROXMOX3_HREF: ${HOMEPAGE_VAR_PROXMOX3_HREF}
      HOMEPAGE_VAR_PIHOLE_HREF: ${HOMEPAGE_VAR_PIHOLE_HREF}
      HOMEPAGE_VAR_PIHOLE_URL: ${HOMEPAGE_VAR_PIHOLE_URL}
      HOMEPAGE_VAR_PIHOLE_KEY: ${HOMEPAGE_VAR_PIHOLE_KEY}
      HOMEPAGE_VAR_PIHOLE_2_HREF: ${HOMEPAGE_VAR_PIHOLE_2_HREF}
      HOMEPAGE_VAR_PIHOLE_2_URL: ${HOMEPAGE_VAR_PIHOLE_2_URL}
      HOMEPAGE_VAR_PIHOLE_2_KEY: ${HOMEPAGE_VAR_PIHOLE_2_KEY}
      HOMEPAGE_VAR_PIHOLE_3_HREF: ${HOMEPAGE_VAR_PIHOLE_3_HREF}
      HOMEPAGE_VAR_PIHOLE_3_URL: ${HOMEPAGE_VAR_PIHOLE_3_URL}
      HOMEPAGE_VAR_PIHOLE_3_KEY: ${HOMEPAGE_VAR_PIHOLE_3_KEY}
      HOMEPAGE_VAR_NPM_HREF: ${HOMEPAGE_VAR_NPM_HREF}
      HOMEPAGE_VAR_NPM_USERNAME: ${HOMEPAGE_VAR_NPM_USERNAME}
      HOMEPAGE_VAR_NPM_PASSWORD: ${HOMEPAGE_VAR_NPM_PASSWORD}
      HOMEPAGE_VAR_HA_HREF: ${HOMEPAGE_VAR_HA_HREF}
      HOMEPAGE_VAR_PORTAINER_HREF: ${HOMEPAGE_VAR_PORTAINER_HREF}
      HOMEPAGE_VAR_PORTAINER_KEY: ${HOMEPAGE_VAR_PORTAINER_KEY}
      HOMEPAGE_VAR_GRAFANA_HREF: ${HOMEPAGE_VAR_GRAFANA_HREF}
      HOMEPAGE_VAR_INFLUXDB_HREF: ${HOMEPAGE_VAR_INFLUXDB_HREF}
      HOMEPAGE_VAR_ZIGBEE_HREF: ${HOMEPAGE_VAR_ZIGBEE_HREF}
      HOMEPAGE_VAR_NAS_HREF: ${HOMEPAGE_VAR_NAS_HREF}
      HOMEPAGE_VAR_JELLYFIN_HREF: ${HOMEPAGE_VAR_JELLYFIN_HREF}
      HOMEPAGE_VAR_QBITTORRENT_HREF: ${HOMEPAGE_VAR_QBITTORRENT_HREF}
      HOMEPAGE_VAR_SPEEDTEST_HREF: ${HOMEPAGE_VAR_SPEEDTEST_HREF}
      HOMEPAGE_VAR_LEXBOT2_HREF: ${HOMEPAGE_VAR_LEXBOT2_HREF}