- Infrastructure:
    - UniFi Network:
        href: https://unifi.ui.com/
        icon: unifi
    - Proxmox Node 1:
        href: {{HOMEPAGE_VAR_PROXMOX1_HREF}}
        icon: proxmox
        ping: {{HOMEPAGE_VAR_PROXMOX1_URL}}
    - Proxmox Node 2:
        href: {{HOMEPAGE_VAR_PROXMOX2_HREF}}
        icon: proxmox
        ping: {{HOMEPAGE_VAR_PROXMOX2_URL}}
    - Proxmox Node 3:
        href: {{HOMEPAGE_VAR_PROXMOX3_HREF}}
        icon: proxmox
        ping: {{HOMEPAGE_VAR_PROXMOX3_URL}}
    - Pi-hole:
        href: {{HOMEPAGE_VAR_PIHOLE_HREF}}
        icon: pi-hole
        ping: {{HOMEPAGE_VAR_PIHOLE_URL}}
        widget:
          type: pihole
          version: 6
          url: {{HOMEPAGE_VAR_PIHOLE_URL}}
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Pi-hole 2:
        href: {{HOMEPAGE_VAR_PIHOLE_2_HREF}}
        icon: pi-hole
        ping: {{HOMEPAGE_VAR_PIHOLE_2_URL}}
        widget:
          type: pihole
          version: 6
          url: {{HOMEPAGE_VAR_PIHOLE_2_URL}}
          key: {{HOMEPAGE_VAR_PIHOLE_2_KEY}}
    - Pi-hole 3:
        href: {{HOMEPAGE_VAR_PIHOLE_3_HREF}}
        icon: pi-hole
        ping: {{HOMEPAGE_VAR_PIHOLE_3_URL}}
        widget:
          type: pihole
          version: 6
          url: {{HOMEPAGE_VAR_PIHOLE_3_URL}}
          key: {{HOMEPAGE_VAR_PIHOLE_3_KEY}}
    - Nginx Proxy Manager:
        href: {{HOMEPAGE_VAR_NPM_HREF}}
        icon: nginx
        ping: {{HOMEPAGE_VAR_NPM_HREF}}
        widget:
            type: npm
            url: {{HOMEPAGE_VAR_NPM_HREF}}
            username: {{HOMEPAGE_VAR_NPM_USERNAME}}
            password: {{HOMEPAGE_VAR_NPM_PASSWORD}}
    - Portainer:
        href: {{HOMEPAGE_VAR_PORTAINER_HREF}}
        ping: {{HOMEPAGE_VAR_PORTAINER_HREF}}
        icon: portainer
        widget:
            type: portainer
            url: {{HOMEPAGE_VAR_PORTAINER_HREF}}
            env: 3
            kubernetes: false # optional, defaults to false
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Grafana:
        href: {{HOMEPAGE_VAR_GRAFANA_HREF}}
        ping: {{HOMEPAGE_VAR_GRAFANA_HREF}}
        icon: grafana
    - InfluxDB:
        href: {{HOMEPAGE_VAR_INFLUXDB_HREF}}
        ping: {{HOMEPAGE_VAR_INFLUXDB_HREF}}
        icon: influxdb
    - Zigbee:
        href: {{HOMEPAGE_VAR_ZIGBEE_HREF}}
        ping: {{HOMEPAGE_VAR_ZIGBEE_HREF}}
        icon: zigbee
- Services:
    - Home Assistant:
        href: {{HOMEPAGE_VAR_HA_HREF}}
        ping: {{HOMEPAGE_VAR_HA_HREF}}
        icon: home-assistant
    - NAS:
        href: {{HOMEPAGE_VAR_NAS_HREF}}
        ping: {{HOMEPAGE_VAR_NAS_HREF}}
        icon: unifi
    - Speedtest:
        href: {{HOMEPAGE_VAR_SPEEDTEST_HREF}}
        ping: {{HOMEPAGE_VAR_SPEEDTEST_HREF}}
        icon: openspeedtest
    - LexBot2:
        href: {{HOMEPAGE_VAR_LEXBOT2_HREF}}
        ping: {{HOMEPAGE_VAR_LEXBOT2_HREF}}
        icon: mdi-robot
- Media:
    - Sonos:
        href: https://play.sonos.com
        icon: sonos
    - Spotify:
        href: https://open.spotify.com
        icon: spotify
    - Jellyfin:
        href: {{HOMEPAGE_VAR_JELLYFIN_HREF}}
        icon: jellyfin
        ping: {{HOMEPAGE_VAR_JELLYFIN_HREF}}
    - Plex:
        href: https://app.plex.tv/desktop/#!/
        icon: plex
    - qBittorrent:
        href: {{HOMEPAGE_VAR_QBITTORRENT_HREF}}
        icon: qbittorrent
        ping: {{HOMEPAGE_VAR_QBITTORRENT_HREF}}
    

